site_name: "de.NBI Cloud Wiki"                         
docs_dir: wiki
theme:
  name: material
  palette:
    primary: 'light blue'
    accent: 'light blue'
  logo: 'img/denbi.svg'
  favicon: 'img/denbi.svg'
repo_name: 'deNBI/cloud-user-docs'
repo_url: 'https://github.com/deNBI/cloud-user-docs' 
edit_uri: blob/master/wiki/
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
nav:
  - 'Home' : 'index.md'
  - 'Portal' : 
    - 'Allocation': portal/allocation.md
    - 'Modification': portal/modification.md
    - 'Project Overview': portal/project_overview.md
    - 'Simple VM': 
      - 'Project': portal/simple_vm_project.md
      - 'Volumes': portal/volumes.md
      - 'Snapshots': portal/snapshots.md
      - 'Customization': portal/customization.md
    - 'User Information': portal/user_information.md
    - 'Personal Data': portal/personal_data.md
  - 'Registration' : registration.md
  - 'OpenStack Quickstart' : 'quickstart.md'
  - 'Concept' : 
    - 'OpenStack Basics' : Concept/basics.md
  - 'Security' : security.md
  - 'Tutorials' :
    - 'Access de.NBI Virtual Machines from Windows 10' : Tutorials/Win10_SSH/index.md
    - 'Access a Simple VM with Mosh' : Tutorials/Mosh/index.md
    - 'SimpleVM File Transfer' : Tutorials/File_Transfer_Methods/index.md
    - 'Bibigrid' : Tutorials/BiBiGrid/index.md
    - 'Blast on BiBiGrid' : Tutorials/BlastOnBiBiGrid/index.md
    - 'Object Storage' : Tutorials/ObjectStorage/index.md
    - 'UserData' : Tutorials/UserData/index.md
    - 'Save FloatingIPs' : Tutorials/SaveFloatingIPs/index.md
    - 'Set up RStudio' : Tutorials/RStudio_Server/index.md
    - 'Theia Web IDE': Tutorials/TheiaIde/index.md
  - 'FAQ' : 'FAQ.md'
  - 'Compute Center Specific' :
    - 'Giessen' : Compute_Center/Giessen.md
    - 'Bielefeld' : Compute_Center/Bielefeld.md
    - 'Heidelberg' : Compute_Center/Heidelberg.md
    - 'Tuebingen' : Compute_Center/Tuebingen.md
    - 'Freiburg' : Compute_Center/Freiburg.md
    - 'Heidelberg DKFZ' : Compute_Center/Heidelberg-DKFZ.md
    - 'Berlin' : Compute_Center/Berlin.md
  - 'Cloud Admin': 
    - 'Configure OpenStack to use Elixir AAI via OpenID Connect': cloud_admin/elixir_OIDC.md
    - 'Register your identity provider for ELIXIR': cloud_admin/identity_provider.md
    - 'News Management': cloud_admin/news_management.md
